services:

  "demo-changesets-2.x":
    profiles: ["demo-changesets-2.x"]
    build:
      context: external-tests/demo-changesets-2.x
      dockerfile: Dockerfile.external-test
      target: ${DOCKER_BUILD_TARGET:-default}
    working_dir: /app-demo-changesets-2.x
    volumes:
      - ./external-tests/demo-changesets-2.x/src:/app-demo-changesets-2.x/src
    init: true
